platform :ios, '15.0'

# Flutter ichki sozlamalarini yuklash
flutter_ios_podfile_setup = File.join(File.dirname(__FILE__), '.symlinks', 'flutter', 'ios', 'podhelper.rb')
if File.exist?(flutter_ios_podfile_setup)
  require flutter_ios_podfile_setup
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  if respond_to?(:flutter_install_all_ios_pods)
    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if respond_to?(:flutter_additional_ios_build_settings)
      flutter_additional_ios_build_settings(target)
    end
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
